name: deploy-container

on:
  push:
    branches:
      - main
    paths:
      - 'packages/container/**'

defaults:
  run:
    working-directory: packages/container

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Install nodejs modules
        run: yarn install
      - name: Build the application
        run: yarn build
      - name: Upload the app to blob storage
        uses: azure/CLI@v1
        with:
          azcliversion: 2.18.0
          inlineScript: |
            az storage blob upload-batch --account-name 'schultmfp' --destination '$web' --destination-path '/container/latest' -s 'packages/container/dist'
      - name: Purge pre-loaded content for the CDN endpoint
        uses: azure/CLI@v1
        with:
          azcliversion: 2.18.0
          inlineScript: |
            az cdn endpoint purge --content-paths '/container/*' --profile-name 'schult-mfp' --name 'schultmfp' --resource-group 'work'
